# Generated by Django 4.0.4 on 2022-04-27 06:13

import CVGenProjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVGenProjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CVGenProjects.models.upload_image_path),
        ),
    ]
