# Generated by Django 4.0.4 on 2022-05-03 07:05

import CVGenExperiences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVGenExperiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=CVGenExperiences.models.upload_image_path),
        ),
    ]
