# Generated by Django 4.0.4 on 2022-04-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=150)),
                ('birthyear', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('1', 'Creative CV'), ('2', 'I’mRex'), ('3', 'Material CV'), ('4', 'Material Resume'), ('5', 'Right Resume')], default='1', max_length=40)),
                ('about', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
