# Generated by Django 4.0.4 on 2022-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVGenBasicInfo', '0003_alter_userbasicinfo_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='template',
            field=models.CharField(choices=[('1', 'Creative CV'), ('2', 'I’mRex'), ('3', 'Material CV'), ('4', 'Material Resume'), ('5', 'Right Resume')], default=('2', 'I’mRex'), max_length=40),
        ),
    ]
